
BEGIN TRAN
--ROLLBACK TRAN
--COMMIT TRAN
--SELECT @@TRANCOUNT

DECLARE @tmp TABLE 
(
	 name varchar(128)
	,[year] int
	,kind_type varchar(64)
)

SET NOCOUNT ON 
INSERT INTO @tmp VALUES ('9',2009,'bluray')
--INSERT INTO @tmp VALUES ('300',2007,'hddvd')
INSERT INTO @tmp VALUES ('300',2006,'bluray')
INSERT INTO @tmp VALUES ('12 Monkeys',1995,'bluray')
INSERT INTO @tmp VALUES ('2001 A Space Odyssey',1968,'bluray')
INSERT INTO @tmp VALUES ('2010 The Year We Make Contact',1984,'bluray')
INSERT INTO @tmp VALUES ('3:10 To Yuma',2007,'bluray')
INSERT INTO @tmp VALUES ('50 First Dates',2004,'bluray')
INSERT INTO @tmp VALUES ('A Bugs Life',1998,'bluray')
INSERT INTO @tmp VALUES ('A Clockwork Orange',1971,'bluray')
INSERT INTO @tmp VALUES ('A Few Good Men',1992,'bluray')
INSERT INTO @tmp VALUES ('A Midsummer''s Night Sex Comedy',1982,'dvd')
INSERT INTO @tmp VALUES ('Ace Ventura: Pet Detective',1994,'m4v')
INSERT INTO @tmp VALUES ('Adventureland',2009,'bluray')
INSERT INTO @tmp VALUES ('Aeon Flux',2005,'bluray')
INSERT INTO @tmp VALUES ('Africa',2013,'bluray')
INSERT INTO @tmp VALUES ('Alien',1979,'bluray')
INSERT INTO @tmp VALUES ('Alien III',1992,'bluray')
INSERT INTO @tmp VALUES ('Alien Resurrection',1997,'bluray')
INSERT INTO @tmp VALUES ('Aliens',1986,'bluray')
INSERT INTO @tmp VALUES ('Ancient Aliens Season 3',2011,'m4v')
INSERT INTO @tmp VALUES ('Annie Hall',1977,'dvd')
INSERT INTO @tmp VALUES ('Antz',2002,'dvd')
INSERT INTO @tmp VALUES ('Armed and Dangerous',1986,'bluray')
INSERT INTO @tmp VALUES ('Arrested Development Season 1',2003,'dvd')
INSERT INTO @tmp VALUES ('Arrested Development Season 2',2004,'dvd')
INSERT INTO @tmp VALUES ('Arrested Development Season 3',2005,'dvd')
INSERT INTO @tmp VALUES ('Attenborough''s Life Stories',2012,'bluray')
INSERT INTO @tmp VALUES ('Austin Powers',1997,'dvd')
INSERT INTO @tmp VALUES ('Austin Powers Gold Member',2002,'dvd')
INSERT INTO @tmp VALUES ('Austin Powers The Spy Who Shagged me',1999,'dvd')
INSERT INTO @tmp VALUES ('Avatar',2009,'bluray')
INSERT INTO @tmp VALUES ('Aziz Ansari:Dangerously Delicious',2012,'m4v')
INSERT INTO @tmp VALUES ('Aziz Ansari:Intimates Moments for a Sensual Evening',2010,'m4v')
INSERT INTO @tmp VALUES ('Band of Brothers',2001,'dvd')
INSERT INTO @tmp VALUES ('Batman Begins',2005,'bluray')
INSERT INTO @tmp VALUES ('Battlestar Galactica Season 1',2004,'bluray')
INSERT INTO @tmp VALUES ('Battlestar Galactica Season 2',2005,'bluray')
INSERT INTO @tmp VALUES ('Battlestar Galactica Season 3',2006,'bluray')
INSERT INTO @tmp VALUES ('Battlestar Galactica Season 4',2007,'bluray')
INSERT INTO @tmp VALUES ('Battlestar Galactica The Plan',2009,'bluray')
INSERT INTO @tmp VALUES ('Blade Runner (Director''s Cut)',1992,'bluray')
INSERT INTO @tmp VALUES ('Blade Runner (Final Cut)',2007,'bluray')
INSERT INTO @tmp VALUES ('Blade Runner (Theatrical Release)',1982,'bluray')
INSERT INTO @tmp VALUES ('Blazing Saddles',1974,'bluray')
INSERT INTO @tmp VALUES ('Blood Diamond',2006,'hddvd')
INSERT INTO @tmp VALUES ('Body of Lies',2008,'bluray')
INSERT INTO @tmp VALUES ('Bottle Rocket',1996,'dvd')
INSERT INTO @tmp VALUES ('Bourne Identity (Trilogy)',2002,'bluray')
INSERT INTO @tmp VALUES ('Bourne Supremacy (Trilogy)',2004,'bluray')
INSERT INTO @tmp VALUES ('Bourne Ultimatum (Trilogy) ',2007,'bluray')
INSERT INTO @tmp VALUES ('Bram Stoker''s Dracula',1992,'bluray')
INSERT INTO @tmp VALUES ('Brave Heart',1995,'bluray')
INSERT INTO @tmp VALUES ('Brazil',1985,'bluray')
INSERT INTO @tmp VALUES ('Breach',2006,'dvd')
INSERT INTO @tmp VALUES ('Brian Regan: The Epitome of Hyperbole',2008,'m4v')
INSERT INTO @tmp VALUES ('Broadway Danny Rose',1984,'dvd')
INSERT INTO @tmp VALUES ('Californication Season 1',2007,'m4v')
INSERT INTO @tmp VALUES ('Californication Season 2',2008,'m4v')
INSERT INTO @tmp VALUES ('Californication Season 3',2009,'m4v')
INSERT INTO @tmp VALUES ('Cars',2006,'bluray')
INSERT INTO @tmp VALUES ('Casino Royale',2006,'bluray')
INSERT INTO @tmp VALUES ('Chaos Theory',2008,'m4v')
INSERT INTO @tmp VALUES ('Charlie''s Angels',2000,'dvd')
INSERT INTO @tmp VALUES ('Chidren Of Men',2006,'dvd')
INSERT INTO @tmp VALUES ('Chronicles of Riddick',2004,'dvd')
INSERT INTO @tmp VALUES ('Clash of the Titans',2010,'bluray')
INSERT INTO @tmp VALUES ('Clear and Present Danger',1994,'bluray')
INSERT INTO @tmp VALUES ('Close Encounters of the Third Kind',1977,'bluray')
INSERT INTO @tmp VALUES ('Cold Comfort Farm',1995,'m4v')
INSERT INTO @tmp VALUES ('Cold Mountain',2003,'bluray')
INSERT INTO @tmp VALUES ('Comedy Central Stand Up: Louis C.K.',2001,'m4v')
INSERT INTO @tmp VALUES ('Community Season 1',2009,'dvd')
INSERT INTO @tmp VALUES ('Community Season 2',2010,'m4v')
INSERT INTO @tmp VALUES ('Confessions of a Dangerous Mind',2002,'bluray')
INSERT INTO @tmp VALUES ('Constantine',2005,'bluray')
INSERT INTO @tmp VALUES ('Contact',1997,'bluray')
INSERT INTO @tmp VALUES ('Copycat',1995,'bluray')
INSERT INTO @tmp VALUES ('Coraline',2009,'bluray')
INSERT INTO @tmp VALUES ('Crimes and Misdemeanors',1989,'dvd')
INSERT INTO @tmp VALUES ('Crouching Tiger Hidden Dragon',2000,'bluray')
INSERT INTO @tmp VALUES ('Dances With Wolves',1990,'bluray')
INSERT INTO @tmp VALUES ('Daniel Tosh: Completely Serious',2007,'m4v')
INSERT INTO @tmp VALUES ('Daniel Tosh: Happy Thoughts',2011,'m4v')
INSERT INTO @tmp VALUES ('Daredevil (Director''s Cut)',2002,'bluray')
INSERT INTO @tmp VALUES ('Dark Fury',2004,'dvd')
INSERT INTO @tmp VALUES ('Date Night ( Extended Cut )',2010,'m4v')
INSERT INTO @tmp VALUES ('Daybreakers',2010,'bluray')
INSERT INTO @tmp VALUES ('Dead Calm',1988,'bluray')
INSERT INTO @tmp VALUES ('Deconstructing Harry',1998,'dvd')
INSERT INTO @tmp VALUES ('Defiance',2008,'bluray')
INSERT INTO @tmp VALUES ('Deja Vu',2007,'dvd')
INSERT INTO @tmp VALUES ('Dexter Season 1',2006,'m4v')
INSERT INTO @tmp VALUES ('Dexter Season 2',2007,'m4v')
INSERT INTO @tmp VALUES ('Dexter Season 3',2008,'m4v')
INSERT INTO @tmp VALUES ('Dexter Season 4',2009,'m4v')
INSERT INTO @tmp VALUES ('Dexter Season 5',2010,'m4v')
INSERT INTO @tmp VALUES ('Dexter Season 6',2011,'m4v')
INSERT INTO @tmp VALUES ('Die Hard',1988,'bluray')
INSERT INTO @tmp VALUES ('Die Hard II Die Harder',1990,'bluray')
INSERT INTO @tmp VALUES ('Die Hard With a Vengeance',1995,'bluray')
INSERT INTO @tmp VALUES ('Dispicable Me',2009,'bluray')
INSERT INTO @tmp VALUES ('Django Unchained',2012,'bluray')
INSERT INTO @tmp VALUES ('Dress To Kill',1998,'dvd')
INSERT INTO @tmp VALUES ('Dumb and Dumber',1994,'bluray')
INSERT INTO @tmp VALUES ('Duplicity',2009,'bluray')
INSERT INTO @tmp VALUES ('Edward Scissorhands',1990,'bluray')
INSERT INTO @tmp VALUES ('Enemy at the Gates',2001,'bluray')
INSERT INTO @tmp VALUES ('Enemy of the State',1998,'bluray')
INSERT INTO @tmp VALUES ('Ever After: A Cinderella Story',2008,'m4v')
INSERT INTO @tmp VALUES ('Everyone Says I Love You ',1996,'dvd')
INSERT INTO @tmp VALUES ('Everything you always wanted to know about sex but were afraid to ask',1972,'dvd')
INSERT INTO @tmp VALUES ('Face Off',1997,'dvd')
INSERT INTO @tmp VALUES ('Falling Skies Season 1 Pilot',2011,'m4v')
INSERT INTO @tmp VALUES ('Fantastic 4',2005,'bluray')
INSERT INTO @tmp VALUES ('Fantastic 4 Rise of the Silver Surfer',2007,'bluray')
INSERT INTO @tmp VALUES ('Fantastic Mr. Fox',2009,'bluray')
INSERT INTO @tmp VALUES ('Fargo',1996,'m4v')
INSERT INTO @tmp VALUES ('Fawlty Towers',1975,'dvd')
INSERT INTO @tmp VALUES ('Fight Club',1999,'bluray')
INSERT INTO @tmp VALUES ('Final Fantasy The Spirits Within',2001,'dvd')
INSERT INTO @tmp VALUES ('Final Fantasy VII Advent Children',2009,'bluray')
INSERT INTO @tmp VALUES ('Frantic',1987,'dvd')
INSERT INTO @tmp VALUES ('Frozen Planet',2011,'bluray')
--INSERT INTO @tmp VALUES ('Full Metal Jacket',1987,'hddvd')
INSERT INTO @tmp VALUES ('Full Metal Jacket',1987,'bluray')
INSERT INTO @tmp VALUES ('G.I. Joe The Rise of Cobra',2009,'bluray')
INSERT INTO @tmp VALUES ('Galapagos',2006,'bluray')
INSERT INTO @tmp VALUES ('Gattaca',1997,'bluray')
INSERT INTO @tmp VALUES ('Get Shorty',1995,'dvd')
INSERT INTO @tmp VALUES ('Ghost Town',2008,'bluray')
INSERT INTO @tmp VALUES ('Good Will Hunting',1997,'bluray')
INSERT INTO @tmp VALUES ('Goodfellas',1990,'bluray')
INSERT INTO @tmp VALUES ('Green Lantern (Extended Cut)',2011,'bluray')
INSERT INTO @tmp VALUES ('Grosse Point Blank',1997,'dvd')
INSERT INTO @tmp VALUES ('Groundhog Day',1993,'dvd')
INSERT INTO @tmp VALUES ('Hancock',2008,'bluray')
INSERT INTO @tmp VALUES ('Happy Gilmore',1998,'dvd')
INSERT INTO @tmp VALUES ('High Anxiety',1977,'bluray')
INSERT INTO @tmp VALUES ('History of The World Part 1',1981,'bluray')
INSERT INTO @tmp VALUES ('Homeland - Season 1',2011,'bluray')
INSERT INTO @tmp VALUES ('House Season 8 Episode 2',2011,'m4v')
INSERT INTO @tmp VALUES ('Human Planet',2011,'bluray')
INSERT INTO @tmp VALUES ('I (Heart) Huckabees',2004,'dvd')
INSERT INTO @tmp VALUES ('I Am Legend',2007,'bluray')
INSERT INTO @tmp VALUES ('I Robot',2004,'dvd')
INSERT INTO @tmp VALUES ('Ice Age',2002,'bluray')
INSERT INTO @tmp VALUES ('Ice Age II Meltdown',2006,'bluray')
INSERT INTO @tmp VALUES ('Inception',2010,'bluray')
INSERT INTO @tmp VALUES ('Inglorious Bastards',2009,'bluray')
INSERT INTO @tmp VALUES ('Inside Man',2006,'dvd')
INSERT INTO @tmp VALUES ('Interview with the Vampire',1994,'bluray')
INSERT INTO @tmp VALUES ('Invincible',2006,'bluray')
INSERT INTO @tmp VALUES ('Iron Man',2008,'bluray')
INSERT INTO @tmp VALUES ('Iron Man II',2010,'bluray')
INSERT INTO @tmp VALUES ('Jim Gaffigan: Beyond the Pale',2006,'m4v')
INSERT INTO @tmp VALUES ('John Carter',2012,'bluray')
INSERT INTO @tmp VALUES ('John Q',2002,'bluray')
INSERT INTO @tmp VALUES ('Jurassic Park',1993,'dvd')
INSERT INTO @tmp VALUES ('Jurassic Park III',2001,'dvd')
INSERT INTO @tmp VALUES ('Jurassic Park The Lost World',1997,'dvd')
INSERT INTO @tmp VALUES ('Just Friends',2005,'dvd')
INSERT INTO @tmp VALUES ('Kill Bill Volume I',2003,'dvd')
INSERT INTO @tmp VALUES ('Kill Bill Volume II',2003,'dvd')
INSERT INTO @tmp VALUES ('Kiss Kiss Bang Bang',2005,'bluray')
INSERT INTO @tmp VALUES ('Knight and Day',2010,'bluray')
INSERT INTO @tmp VALUES ('Kung Fu Hustle',2004,'bluray')
INSERT INTO @tmp VALUES ('Ladyhawke',1985,'dvd')
INSERT INTO @tmp VALUES ('Leon The Professional',1994,'bluray')
INSERT INTO @tmp VALUES ('Liar Liar',1997,'m4v')
INSERT INTO @tmp VALUES ('Life',2010,'bluray')
INSERT INTO @tmp VALUES ('Live Free or Die Hard',2007,'bluray')
INSERT INTO @tmp VALUES ('Lord of the Rings Return of the King',2003,'bluray')
INSERT INTO @tmp VALUES ('Lord of the Rings The Fellowship of the Ring',2001,'bluray')
INSERT INTO @tmp VALUES ('Lord of the Rings The Two Towers',2002,'bluray')
INSERT INTO @tmp VALUES ('Lost in Translation',2003,'m4v')
INSERT INTO @tmp VALUES ('Louie Season 1',2010,'bluray')
INSERT INTO @tmp VALUES ('Louie Season 2',2011,'m4v')
INSERT INTO @tmp VALUES ('Louie Season 3',2012,'m4v')
INSERT INTO @tmp VALUES ('Louis C.K.: Chewed Up',2008,'m4v')
INSERT INTO @tmp VALUES ('Louis C.K.: Hilarious',2010,'m4v')
INSERT INTO @tmp VALUES ('Louis C.K.: Live at the Beacon',2011,'m4v')
INSERT INTO @tmp VALUES ('Love And Death',1975,'dvd')
INSERT INTO @tmp VALUES ('Lucky # Slevin',2005,'dvd')
INSERT INTO @tmp VALUES ('Madagascar',2011,'bluray')
INSERT INTO @tmp VALUES ('Magnolia',1999,'bluray')
INSERT INTO @tmp VALUES ('Mallrats',1995,'hddvd')
INSERT INTO @tmp VALUES ('Man On Fire',2004,'dvd')
INSERT INTO @tmp VALUES ('Manhattan',1979,'dvd')
INSERT INTO @tmp VALUES ('Mansfield Park',1999,'m4v')
INSERT INTO @tmp VALUES ('Marjoe',1972,'dvd')
INSERT INTO @tmp VALUES ('Matchpoint',2005,'bluray')
INSERT INTO @tmp VALUES ('Matrix Reloaded',2003,'bluray')
INSERT INTO @tmp VALUES ('Matrix Revolutions',2003,'bluray')
INSERT INTO @tmp VALUES ('Melinda and Melinda',2005,'dvd')
INSERT INTO @tmp VALUES ('Mercury Rising',1998,'dvd')
INSERT INTO @tmp VALUES ('Michael Clayton',2007,'bluray')
INSERT INTO @tmp VALUES ('Midnight in Paris',2011,'m4v')
INSERT INTO @tmp VALUES ('Midnight in the Garden of Good and Evil',1997,'m4v')
INSERT INTO @tmp VALUES ('Mighty Aphrodite',1995,'dvd')
INSERT INTO @tmp VALUES ('Minority Report',2002,'bluray')
INSERT INTO @tmp VALUES ('Mission Impossible I',1996,'bluray')
INSERT INTO @tmp VALUES ('Mission Impossible II',2000,'bluray')
INSERT INTO @tmp VALUES ('Mission Impossible III',2006,'bluray')
INSERT INTO @tmp VALUES ('Mission Impossible IV Ghost Protocol',2011,'bluray')
INSERT INTO @tmp VALUES ('Monster''s Inc.',2001,'bluray')
INSERT INTO @tmp VALUES ('Monty Python and the Holy Grail',1975,'bluray')
INSERT INTO @tmp VALUES ('Moon',2009,'bluray')
INSERT INTO @tmp VALUES ('Moonrise Kingdom',2012,'bluray')
INSERT INTO @tmp VALUES ('Mr. & Mrs. Smith',2005,'bluray')
INSERT INTO @tmp VALUES ('Mr. Universe',2012,'m4v')
INSERT INTO @tmp VALUES ('Napolean Dynamite',2004,'dvd')
INSERT INTO @tmp VALUES ('National Lampoon''s Van Wilder',2002,'m4v')
INSERT INTO @tmp VALUES ('Nature''s Most Amazing Events',2009,'bluray')
INSERT INTO @tmp VALUES ('New York Stories',1989,'bluray')
INSERT INTO @tmp VALUES ('Next',2007,'dvd')
INSERT INTO @tmp VALUES ('Night at the Museum',2006,'bluray')
INSERT INTO @tmp VALUES ('No Country For Old Men',2007,'bluray')
INSERT INTO @tmp VALUES ('Nothing But Trouble',1998,'dvd')
INSERT INTO @tmp VALUES ('Oceans Thirteen',2007,'bluray')
INSERT INTO @tmp VALUES ('Oceans Twelve',2004,'bluray')
INSERT INTO @tmp VALUES ('Office Space',1999,'dvd')
INSERT INTO @tmp VALUES ('Out Of England',2008,'dvd')
INSERT INTO @tmp VALUES ('Out of Sight',1998,'bluray')
INSERT INTO @tmp VALUES ('Pan''s Labyrinth',2006,'bluray')
INSERT INTO @tmp VALUES ('Paper Man',2009,'bluray')
INSERT INTO @tmp VALUES ('Paycheck',2003,'dvd')
INSERT INTO @tmp VALUES ('Pitch Black',1999,'dvd')
INSERT INTO @tmp VALUES ('Pixar Short Films',2007,'bluray')
INSERT INTO @tmp VALUES ('Planes Trains and Automobiles',1987,'bluray')
INSERT INTO @tmp VALUES ('Planet Earth',2007,'bluray')
INSERT INTO @tmp VALUES ('Point Break ',1991,'bluray')
INSERT INTO @tmp VALUES ('Point of No Return',1998,'dvd')
INSERT INTO @tmp VALUES ('Predator',1987,'dvd')
INSERT INTO @tmp VALUES ('Prince of Persia: The Sands of Time',2010,'m4v')
INSERT INTO @tmp VALUES ('Prometheus',2012,'bluray')
INSERT INTO @tmp VALUES ('Pulp Fiction',1994,'bluray')
INSERT INTO @tmp VALUES ('Punchdrunk Love',2003,'dvd')
INSERT INTO @tmp VALUES ('Quantam of Solace',2008,'bluray')
INSERT INTO @tmp VALUES ('Radio Days',1987,'dvd')
INSERT INTO @tmp VALUES ('Raiders of the Lost Ark',1981,'dvd')
INSERT INTO @tmp VALUES ('Ratatouille',2007,'bluray')
INSERT INTO @tmp VALUES ('Red Planet',2000,'bluray')
INSERT INTO @tmp VALUES ('Remember the Titans',2000,'m4v')
INSERT INTO @tmp VALUES ('Reno 911 Season 1',2003,'dvd')
INSERT INTO @tmp VALUES ('Reno 911 Season 2',2004,'dvd')
INSERT INTO @tmp VALUES ('Reno 911 Season 3',2005,'dvd')
INSERT INTO @tmp VALUES ('Reservoir Dogs',1992,'bluray')
INSERT INTO @tmp VALUES ('Righteous Kill',2008,'bluray')
INSERT INTO @tmp VALUES ('Robin Hood: Men In Tights',1993,'bluray')
INSERT INTO @tmp VALUES ('Robinhood',2010,'bluray')
INSERT INTO @tmp VALUES ('Role Models',2008,'m4v')
INSERT INTO @tmp VALUES ('Safehouse',2012,'bluray')
INSERT INTO @tmp VALUES ('Scoop',2006,'m4v')
INSERT INTO @tmp VALUES ('Scrooged ',1988,'bluray')
INSERT INTO @tmp VALUES ('Se7en',1995,'bluray')
INSERT INTO @tmp VALUES ('Shadows and Fog',1992,'dvd')
INSERT INTO @tmp VALUES ('Sherlock Holmes',2009,'bluray')
INSERT INTO @tmp VALUES ('Sherlock Holmes A Game of Shadows',2011,'bluray')
INSERT INTO @tmp VALUES ('Shoot To Kill',1988,'dvd')
INSERT INTO @tmp VALUES ('Shooter',2007,'dvd')
INSERT INTO @tmp VALUES ('Shutter Island',2010,'bluray')
INSERT INTO @tmp VALUES ('Silent Movie',1976,'bluray')
INSERT INTO @tmp VALUES ('Silver Linings Playbook',2012,'bluray')
INSERT INTO @tmp VALUES ('Sling Blade',1996,'bluray')
INSERT INTO @tmp VALUES ('Snatch',2000,'bluray')
INSERT INTO @tmp VALUES ('Snow White and the Huntsman',2012,'bluray')
INSERT INTO @tmp VALUES ('Somewhere in Time',1980,'m4v')
INSERT INTO @tmp VALUES ('South Park Bigger Longer and Uncut',1999,'dvd')
INSERT INTO @tmp VALUES ('Spaceballs',1987,'bluray')
INSERT INTO @tmp VALUES ('Spartan',2003,'dvd')
INSERT INTO @tmp VALUES ('Spiderman',2002,'bluray')
INSERT INTO @tmp VALUES ('Spiderman II',2004,'bluray')
INSERT INTO @tmp VALUES ('Spiderman III',2007,'bluray')
INSERT INTO @tmp VALUES ('Spy Game',2002,'dvd')
INSERT INTO @tmp VALUES ('Star Trek',2009,'bluray')
INSERT INTO @tmp VALUES ('Star Wars I Phatom Menace',1999,'bluray')
INSERT INTO @tmp VALUES ('Star Wars II Attack of the Clones',2002,'bluray')
INSERT INTO @tmp VALUES ('Star Wars III Revenge of the Sith',2005,'bluray')
INSERT INTO @tmp VALUES ('Star Wars IV A New Hope',1977,'dvd')
INSERT INTO @tmp VALUES ('Star Wars V The Empire Strikes Back',1980,'dvd')
INSERT INTO @tmp VALUES ('Star Wars VI Return of the Jedi',1983,'dvd')
INSERT INTO @tmp VALUES ('State Of Play',2009,'bluray')
INSERT INTO @tmp VALUES ('Step Brothers',2008,'bluray')
INSERT INTO @tmp VALUES ('Stripes',1981,'bluray')
INSERT INTO @tmp VALUES ('Suckerpunch (Extended Cut)',2011,'bluray')
INSERT INTO @tmp VALUES ('Sunshine',2007,'bluray')
INSERT INTO @tmp VALUES ('Syriana',2005,'dvd')
INSERT INTO @tmp VALUES ('Taken',2008,'bluray')
INSERT INTO @tmp VALUES ('Taking Lives (Extended Cut)',2004,'bluray')
INSERT INTO @tmp VALUES ('Talladega Nights',2006,'bluray')
INSERT INTO @tmp VALUES ('Terminator Salvation (Director''s Cut)',2009,'bluray')
INSERT INTO @tmp VALUES ('The Amazing Spider-Man',2012,'bluray')
INSERT INTO @tmp VALUES ('The Avengers',2012,'bluray')
INSERT INTO @tmp VALUES ('The Book Of Eli',2009,'bluray')
INSERT INTO @tmp VALUES ('The Changeup',2011,'bluray')
INSERT INTO @tmp VALUES ('The Conversation',1974,'bluray')
INSERT INTO @tmp VALUES ('The Darjeeling Limited',2007,'bluray')
INSERT INTO @tmp VALUES ('The Dark Knight',2008,'bluray')
INSERT INTO @tmp VALUES ('The Dark Knight Rises',2012,'bluray')
INSERT INTO @tmp VALUES ('The Departed',2006,'hddvd')
INSERT INTO @tmp VALUES ('The Fifth Element',2007,'bluray')
INSERT INTO @tmp VALUES ('The Ghost Writer',2010,'bluray')
INSERT INTO @tmp VALUES ('The Good Shepherd',2006,'dvd')
INSERT INTO @tmp VALUES ('The Hangover',2009,'m4v')
INSERT INTO @tmp VALUES ('The Hunt for Red October',1990,'bluray')
INSERT INTO @tmp VALUES ('The Illusionist',2006,'bluray')
INSERT INTO @tmp VALUES ('The Incredibles',2003,'dvd')
INSERT INTO @tmp VALUES ('The International',2009,'bluray')
INSERT INTO @tmp VALUES ('The Invention of Lying',2009,'bluray')
INSERT INTO @tmp VALUES ('The Island',2005,'dvd')
INSERT INTO @tmp VALUES ('The Italian Job',2003,'hddvd')
INSERT INTO @tmp VALUES ('The Jackal',1997,'dvd')
INSERT INTO @tmp VALUES ('The Las Samurai',2003,'bluray')
INSERT INTO @tmp VALUES ('The Last Exorcism',2010,'m4v')
INSERT INTO @tmp VALUES ('The Last Samurai',2003,'bluray')
INSERT INTO @tmp VALUES ('The League of Extraordinary Gentlemen',2003,'bluray')
INSERT INTO @tmp VALUES ('The Life Aquatic',2004,'dvd')
INSERT INTO @tmp VALUES ('The Manchurian Candidate',2004,'dvd')
INSERT INTO @tmp VALUES ('The Matrix',1999,'bluray')
INSERT INTO @tmp VALUES ('The Meaning of Life',1983,'dvd')
INSERT INTO @tmp VALUES ('The Nin9s',2006,'dvd')
INSERT INTO @tmp VALUES ('The Ninth Gate',1999,'bluray')
INSERT INTO @tmp VALUES ('The Number 23',2006,'bluray')
INSERT INTO @tmp VALUES ('The Office Complete Series',2001,'dvd')
INSERT INTO @tmp VALUES ('The P.E.A.R Proposition',2005,'dvd')
INSERT INTO @tmp VALUES ('The Passion Of The Christ',2004,'dvd')
INSERT INTO @tmp VALUES ('The Pelican Brief',1993,'bluray')
INSERT INTO @tmp VALUES ('The Prestige',2006,'bluray')
INSERT INTO @tmp VALUES ('The Prince Of Egypt',1998,'dvd')
INSERT INTO @tmp VALUES ('The Princess Bride',1987,'m4v')
INSERT INTO @tmp VALUES ('The Proposal',2009,'bluray')
INSERT INTO @tmp VALUES ('The Purple Rose of Cairo',1984,'dvd')
INSERT INTO @tmp VALUES ('The Rite',2011,'bluray')
INSERT INTO @tmp VALUES ('The Royal Tenenbaums',2001,'m4v')
INSERT INTO @tmp VALUES ('The Shawshank Redemption',1994,'bluray')
INSERT INTO @tmp VALUES ('The Shining',1980,'bluray')
INSERT INTO @tmp VALUES ('The Sixth Sense',1999,'dvd')
INSERT INTO @tmp VALUES ('The Spanish Prisoner',1998,'dvd')
INSERT INTO @tmp VALUES ('The Sum of All Fears',2002,'bluray')
INSERT INTO @tmp VALUES ('The Switch',2010,'bluray')
INSERT INTO @tmp VALUES ('The Tree of Life',2011,'bluray')
INSERT INTO @tmp VALUES ('The Twelve Chairs',1970,'bluray')
INSERT INTO @tmp VALUES ('The Usual Suspects',1995,'bluray')
INSERT INTO @tmp VALUES ('The Walking Dead Season 1',2010,'bluray')
INSERT INTO @tmp VALUES ('The Walking Dead Season 2',2011,'m4v')
INSERT INTO @tmp VALUES ('The Walking Dead Season 3',2012,'m4v')
INSERT INTO @tmp VALUES ('This is Spinal Tap',1984,'dvd')
INSERT INTO @tmp VALUES ('Thoth',2002,'dvd')
INSERT INTO @tmp VALUES ('Three Kings',1999,'dvd')
INSERT INTO @tmp VALUES ('To Be Or Not To Be',1983,'bluray')
INSERT INTO @tmp VALUES ('Tomb Raider',2001,'dvd')
INSERT INTO @tmp VALUES ('Total Recall',1990,'bluray')
INSERT INTO @tmp VALUES ('Training Day',2001,'bluray')
INSERT INTO @tmp VALUES ('Tron Legacy',2010,'bluray')
INSERT INTO @tmp VALUES ('Troy (Director''s Cut)',2007,'bluray')
INSERT INTO @tmp VALUES ('True Romance',1993,'dvd')
INSERT INTO @tmp VALUES ('Ultraviolet',2006,'dvd')
INSERT INTO @tmp VALUES ('Unbreakable',2000,'dvd')
INSERT INTO @tmp VALUES ('Uncle Buck',1989,'bluray')
INSERT INTO @tmp VALUES ('Underworld',2003,'dvd')
INSERT INTO @tmp VALUES ('Underworld Awakening',2012,'m4v')
INSERT INTO @tmp VALUES ('Underworld Evolution',2005,'dvd')
INSERT INTO @tmp VALUES ('Unstoppable',2010,'bluray')
INSERT INTO @tmp VALUES ('V for Vendetta',2005,'bluray')
INSERT INTO @tmp VALUES ('Vicky Cristina Barcelona',2008,'m4v')
INSERT INTO @tmp VALUES ('Waiting',2005,'m4v')
INSERT INTO @tmp VALUES ('Wall E',2008,'bluray')
INSERT INTO @tmp VALUES ('War of the Worlds',2005,'dvd')
INSERT INTO @tmp VALUES ('Watchmen (Director''s Cut)',2009,'bluray')
INSERT INTO @tmp VALUES ('Weapons of Self Destruction',2009,'dvd')
INSERT INTO @tmp VALUES ('What About Bob?',1991,'dvd')
INSERT INTO @tmp VALUES ('Witness',1985,'dvd')
INSERT INTO @tmp VALUES ('Wrath of the Titans',2012,'bluray')
INSERT INTO @tmp VALUES ('X-Files Fight the Future',1998,'bluray')
INSERT INTO @tmp VALUES ('X-Files I Want to Believe',2008,'bluray')
INSERT INTO @tmp VALUES ('X-Men',2000,'bluray')
INSERT INTO @tmp VALUES ('X-Men First Class',2011,'bluray')
INSERT INTO @tmp VALUES ('X-Men Origins Wolverine',2009,'bluray')
INSERT INTO @tmp VALUES ('X-Men The last stand',2006,'bluray')
INSERT INTO @tmp VALUES ('X2 X-Men United',2003,'bluray')
INSERT INTO @tmp VALUES ('Yes Man',2008,'bluray')
INSERT INTO @tmp VALUES ('You Will Meet a Tall Dark Stranger',2010,'m4v')
INSERT INTO @tmp VALUES ('Young Frankenstein',1974,'bluray')
INSERT INTO @tmp VALUES ('Zach Galifianakis: Live at the Purple Onion',2006,'m4v')
INSERT INTO @tmp VALUES ('Zelig',1983,'dvd')
INSERT INTO @tmp VALUES ('Zodiac (Director''s Cut)',2007,'bluray')
INSERT INTO @tmp VALUES ('Zoolander',2001,'dvd')
SET NOCOUNT OFF

--SELECT COUNT(*)
--FROM
--	@tmp tmp
--WHERE
--	tmp.kind_type NOT IN ('m4v', 'hddvd')

INSERT INTO t_album
(
	imdb_id
	,manual_update
	,name
	,[year]
	,updated_date
	,updated_by
)
SELECT
	''					-- 'imdb_id'
	,1					-- 'manual_update'
	,tmp.name			-- 'name'
	,tmp.year			-- 'year'
	,GETDATE()			-- 'updated_date'
	,'jlitfin'			-- 'updated_by'
	--,a.*
FROM
	@tmp tmp
	--INNER JOIN t_album a
	--	ON(tmp.name = a.name)
WHERE
	tmp.kind_type NOT IN ('m4v', 'hddvd')

INSERT INTO t_album_track
(
	name
	,itunes_track_id
	,artist_id
	,album_id
	,genre_id
	,kind_type_id
	,manual_update
	,persistent_id
	,total_time_string
	,track_number
	,updated_date
	,updated_by
)
SELECT
	tmp.name
	,NULL
	,0
	,a.album_id
	,0
	,kt.kind_type_id
	,1
	,NULL
	,''
	,1
	,GETDATE()
	,'jlitfin'
FROM
	@tmp tmp
	INNER JOIN t_album a
		ON(a.manual_update = 1
			AND tmp.name = a.name)
	LEFT JOIN t_kind_type kt
		ON(tmp.kind_type = kt.kind_type_text)
WHERE
	tmp.kind_type NOT IN ('m4v', 'hddvd')